### PR TITLE
Adds a test class for handling model to model comparisons

### PR DESCRIPTION
**Pull request by appukuttan-shailesh**
We recently came across several scenarios where users were interested in carrying out model-to-model comparisons with no experimental data, i.e. observations, involved.

As this seemed of wider utility (for e.g. when comparing the implementation of a particular model across multiple simulators), we found it useful to have a `Test` class targeted for such comparisons, such as the one in this PR.

There naturally exists many similarities (e.g. duplicated methods) between `Test` and `Test_M2M` (could be renamed). If such a test class is to be incorporated, it would probably be ideal to have a `BaseTest` class from which the above two classes could inherit the common parameters/methods. 

Do let us know what you think of this? I would be happy to work on this if you have any suggestions.

### CODE REVIEW

**Comment by rgerkin** [comment]
@appukuttan-shailesh 
This sounds reasonable and I proposed a similar kind of Test in my grant a few years ago.  I think the TestM2M class can just inherit from Test.  I'm not sure there is need for a new base class below Test and TestM2M.  

If you want to work on this I'd be happy to accept it.  I propose that you implement it such instead of argument pairs like "model1,model2", you just use "models", which can then be a tuple or list containing 1 or more models.  This allows TestM2M to possibly generalize to fewer than 2 or to three or more models in some implementations.  Similary, "prediction1,prediction2 would become "predictions". This also allows the number and position of args and kwargs in the Test and TestM2M to be identical, which allows as many Test class methods as possible to be inherited directly, and only overridden when you actually need to check the contents of e.g. "models" for multiple models.  

Is this clear?  If not I can attempt my own implementation first and you can let me know if it works.  

FYI, I pushed a lot of new unit tests and coverage checks to the dev branch recently.  I hope to release 0.2 soon but I think we can get this in if has its own unit tests and everything is still passing.

**Comment by appukuttan-shailesh** [comment]
Hi @rgerkin ,
Happy to see that you think this would be a useful addition. I am more than willing to take this up, especially since we probably have immediate use for this. I had some queries regarding the implementation details:

1) My reason for not sublcassing from `Test` was because it contains `observation` related parameters and methods (e.g. `validate_observation()`) which would then be inherited by `TestM2M`. These would not be required by the model-to-model tests. Should we just let them be there but remain unused?

With the base test class approach, I was thinking we could move all the common features upto the base class. But this I realize could potentially involve more changes elsewhere.

2) Regarding the implementation as a list (or set) of models, I saw that you already have something on these lines here: https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L325
I will have `TestM2M` handle this kind of input.

It would be good to have this included in the 0.2 release. When do you target the release?

**Comment by rgerkin** [comment]
@appukuttan-shailesh 
1) I could be wrong, but I think that observation is still a general enough thing that I'd like it to be a part of the base Test class.  It is easy enough to set `observation=None` and then never use it.  TestM2M's constructor could call `super(TestM2M,self).__init__(None, name=name, **params)`, for example.  Or there could be scenarios where you do use it, like simultaneously comparing the models to each other and to some piece of reference data (for example, maybe all models must produce the same spike times, and furthermore those spike times must match a set of reference spike times). 

2) Yes, you can probably modify that section of code to check if the Test is a TestM2M type, and if so to ignore the TestSuite conversion and proceed directly to the `_judge` calls.  

I may push the release out at any time, but even if I do I am happy to push out a quick 0.2.1 when your PR is ready and tested.

**Comment by appukuttan-shailesh** [comment]
I shall try to have this implemented by the end of this week. Once we think it is ok, we can proceed with the test cases and subsequent release. Thanks again.

**Comment by appukuttan-shailesh** [comment]
@rgerkin : since we are planning to handle multiple models (with or without experimental 'observation'), I think it would be best to have all the models do `generate_prediction()` once to obtain a list of `predictions`. We can then use this list to evaluate scores for each model-model combination. This would avoid having to run the model for each comparison.

To do the above, I would need to alter the way `_judge()` works (for `TestM2M`) and, if ok, simply merge `_judge()` and `judge()`. Would this be ok? Or is there a logical separation that you would like to maintain between these two methods?

**Comment by appukuttan-shailesh** [comment]
@rgerkin : regarding the final 'score' output, I am currently thinking of having it as a 2D list, such as this (e.g. Z-scores):
```
+-------------+-------------+--------+--------+
|             | observation | model1 | model2 |
+-------------+-------------+--------+--------+
| observation |     0.0     |    x   |    y   |
+-------------+-------------+--------+--------+
| model1      |      x      |   0.0  |    z   |
+-------------+-------------+--------+--------+
| model2      |      y      |    z   |   0.0  |
+-------------+-------------+--------+--------+
```
with `x,y,z` only being evaluated only once and being copied over to the corresponding element; diagonal elements would always be best scores (self-compare; added just to complete the score matrix). When there is no observation, those entries will have `None`. Does this seem fine, or do you have any suggestions?

I saw that you have a `ScoreMatrix` class, but it seems to be customised for use with multiple tests (test suite).

**Comment by rgerkin** [comment]
@appukuttan-shailesh 
Concerning multiple calls to generate_prediction:  

You can merge `_judge` and `judge` if you can implement the intended behavior of lines 333-347, which is to distinguish between different kinds of error conditions and user choices about error handling, all within one function.  I prefer the separation of the core functionality and the error handling, but if you need to merge them for some architectural reason that is fine.  

A more valuable long-run strategy might be to have some sort of prediction caching, for example check if the current state of the model has had generate_prediction run on it, and if so it just looks it up the result in a cache.  `sciunit.Model` already has a `state` attribute, which is a hash of the Model's `__dict__`.  So long as the Model does not contain "deep" attributes, like attributes that refer to possibly-changing files, the `sciunit.Model.state` should be a good candidate for a key in a cache dictionary of model predictions.  And if you are concerned about deep attributes, you could just reset this cache at the beginning of `judge`, so that it will only lookup cached predictions made inside the same call to `judge`.  So you would replace:  

```
prediction = self.generate_prediction(model)
```
with
```
if model in self.predictions:
  prediction = self.predictions[model.state]
else:
  prediction = self.generate_prediction (model)
  self.predictions[model.state] = prediction
```

**Comment by rgerkin** [comment]
@appukuttan-shailesh
Model vs Model is symmetric and may not make sense as a Z-score, but maybe it could be a `CohensDScore` (if there is variation), or a `RatioScore` (if there isn't), or a `CorrelationScore` (if the prediction is a vector, note this score type doesn't exist yet) or something like that.  If it was a `CorrelationScore` then the matrix would effectively be a correlation matrix and you could do other cool things like sort it to cluster models.  

I propose that if the TestM2M has an observation of `None`, that you just drop the corresponding row and column from the resulting score table.  

You are right that I don't have a class for a Models vs Models table (ScoreMatrix is Models vs Tests).  However, I think it can probably still use the same machinery (e.g. inheriting from `pandas.DataFrame`).  It may also be possible to add code to `sciunit.ScoreMatrix` to account for this case, to avoid too much code duplication.

**Comment by appukuttan-shailesh** [comment]
@rgerkin : I think I have implemented most of the required changes here. This [Jupyter Notebook](https://github.com/appukuttan-shailesh/PyNN_testData/blob/master/M2M_Example.ipynb) illustrates how this would currently be used.

I have retained both `_judge()` and `judge()` for TestM2M, though the former now has lesser responsibilities. I could infact have merged the two, but tried to keep a similar workflow (to `Test`) as far as I could.

Prediction caching is something that we (@apdavison) have been discussing quite a bit recently. We completely agree that, moving forward, this would be a very useful feature. It might be useful to discuss this further (maybe separately) and have another PR in the near future to add this.

Yes, I was being too narrow-sighted when assuming all scores to be symmetric! Thanks for pointing that out. Have fixed that by having each element evaluated independently. In future, if required, we could have each `score_type` optionally specify whether it is symmetric or not, and update this to improve efficiency.

I went ahead with your suggestion to make use of `pandas.DataFrame` for the scoring matrix. I have created two new classes (`ScoreMatrixM2M` and `ScoreArrayM2M`) to manage this. I did spend a little bit of time figuring out how the existing `sciunit.ScoreMatrix` could be updated to include this use-case, but felt things were turning a bit messy. I have to confess this was the first time I was using pandas, and so probably you might quickly spot a cleaner way to handle this.

As per your suggestion, if the TestM2M has an observation of None, the corresponding row and column is dropped from the resulting score matrix. I agree this does keep things a tad cleaner.

I am pretty sure more error handling would be required. Do let me know if you spot any obvious ones. Will move on to those once we feel the basic implementation is in place.

p.s. some of the things I want you to comment on have been marked `TODO`. These are:
1. Does the `last_model` attribute have any use currently? I have currently not implemented this for `TestM2M` (line 445).
2. I have also not implemented the `optimize()` method in `TestM2M`. Should I keep this as a method that requires user implementation?

**Comment by rgerkin** [comment]
@appukuttan-shailesh Can you add some unit tests that check the behavior of this code in some simple examples?  You can just use some of the some simple models in `sciunit.models` for those tests if you'd like.  I can wrap them in the `unittest` class later if you are not familiar with that part.  

I will be examining this code today in a `shailesh` branch in the master repo.

**Comment by appukuttan-shailesh** [comment]
@rgerkin : Sure, I shall try to create some basic tests. Hope to have them ready before the end of this week. Do let me know if you find anything that can be improved upon.

**Comment by rgerkin** [comment]
@appukuttan-shailesh 
You can look at [this](https://github.com/scidash/neuronunit/blob/master/neuronunit/unit_test/m2m_test.ipynb) for an example.  You can write your tests as notebooks or as python files; I can test them either way in unit test.  Note that the example above will require the latest `neuronunit:master` and `sciunit:shailesh` to run

**Comment by appukuttan-shailesh** [comment]
@rgerkin : I have added a couple of tests (using `unittest`) to `sciunit/unit_test/core_tests.py`:
- test_testm2m_with_observation()
- test_testm2m_without_observation()

Do let me know if these are fine, or if anything needs to be added/changed.

**Comment by rgerkin** [comment]
@appukuttan-shailesh Can you close and reopen this into scidash:shailesh?  The dev branch now has a lot of stuff you don't want to deal with right now.  scidash:shailesh was forked off of master, but reflects the state of dev a few weeks ago when you opened this, plus a bug fix or two I added.  Then the Travis CI build should pass.

**Comment by rgerkin** [comment]
See #57 for continuation.

**Pull request closed without merging**
