### PR TITLE
Test m2m

### PR DESCRIPTION
**Pull request by appukuttan-shailesh**
In continuation to #48 
PR moved to `scidash:shailesh` instead of `dev`

### CODE REVIEW

**Comment by appukuttan-shailesh** [comment]
I suppose I should undo the last two merges.

**Comment by rgerkin** [comment]
Actually, it's OK.  The commits to dev are fine.  I was thinking of neuronunit.

**Comment by appukuttan-shailesh** [comment]
But I think I should remove the `test_versioned` test, which I had merged into mine? Travis seems to have failed because of that.

**Comment by rgerkin** [comment]
I just pulled the stuff from `master` into `shailesh` that is needed for that to pass.  Stand by.

**Comment by rgerkin** [comment]
Everything is merged into `scidash:master` now and should be part of the 0.2 release coming soon.

**Comment by appukuttan-shailesh** [comment]
Great! Looking forward to all the other new features.

**Pull request merged**
